CREATE TABLE Canal(
CanalID INT PRIMARY KEY,
Nome VARCHAR (150) NOT NULL,
ContagemInscritos INT DEFAULT 0,
DataCriacao DATETIME NOT NULL
);

SELECT *
FROM Canal

CREATE TABLE Video (
VideoID INT PRIMARY KEY,
Nome VARCHAR (150) NOT NULL,
Visualizacoes INT DEFAULT 0,
Likes INT DEFAULT 0,
Dislikes INT DEFAULT 0,
Duracao INT NOT NULL,
CanalID INT FOREIGN KEY REFERENCES Canal(CanalID)
);


SELECT *
FROM Video